# Generated by Django 4.2.7 on 2024-02-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('received', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=80)),
                ('orderNumber', models.IntegerField()),
                ('orderedCases', models.IntegerField()),
                ('actualCases', models.IntegerField()),
                ('estimatedWeight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actualWeight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=80)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dsa_backend.product')),
            ],
        ),
    ]
